name: video_trimmer
description: A Flutter package for trimming videos. This supports retrieving,
  trimming, and storage of trimmed video files to the file system.
version: 4.1.0
homepage: https://github.com/samuel-kings/video_trimmer

publish_to: none

environment:
  sdk: ^3.7.0
  flutter: ">=3.3.0"

dependencies:
  ffmpeg_kit_flutter:
    git:
      url: https://github.com/samuel-kings/ffmpeg_flutter_kit_fork.git
      path: flutter/flutter
      ref: main
  flutter:
    sdk: flutter
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  transparent_image: ^2.0.1
  video_player: ^2.9.2

dev_dependencies:
  flutter_lints: ^5.0.0
  lints: ^5.0.0
